SocialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/(?P<username>[-\w]+)/",views.UserPosts.as_view(),name="for_user"),
    path("by/(?P<username>[-\w]+)/(?P<pk>\d+)/",views.PostDetail.as_view(),name="single"),
    path("delete/(?P<pk>\d+)/",views.DeletePost.as_view(),name="delete"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


    <link rel="stylesheet" href="{% static '/SocialNetwork/css/master.css' %}">
    <title>SocialNetwork | {% block title %}{% endblock title %}</title>
</head>
<body>
    {% include 'navbar.html' %}
    
    {% block main_content %}{% endblock main_content %}
    <canvas id="canvas" width="100%" height="50"></canvas>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

<script  src="{% static 'SocialNetwork/js/main.js' %}" type="text/javascript"></script>

</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block main_content %}
 <div class="container">
      {% if messages %}
          {% for message in messages %}
               <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{message}}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                         <span aria-hidden="true">&times;</span>
                    </button>
               </div>
          {% endfor %}
     {% endif %}
     <h1 class="text-center mt-5">Welcome to my Social Network!!!</h1>
</div>
{% endblock main_content %}

templates/navbar.html
<nav class="menu sticky-top navbar navbar-expand-lg navbar-dark mynav">
  <a class="navbar-brand mynav text-info ml-3" href="{% url 'home' %}"><h3>MYSITE</h3></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
      {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link text-light font-weight-bold" href="{% url 'posts:create' %}">Posts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light font-weight-bold" href="{% url 'groups:all' %}">Groups</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light font-weight-bold" href="{% url 'groups:create' %}"> Create Group</a>
      </li>
    </ul>

    <div class="my-2 my-lg-0">
        <a class="mr-sm-2 text-light font-weight-bold" href="{% url 'accounts:logout' %}">Logout</a>
    </div>
    {% else %}
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
           <a class="nav-link text-light font-weight-bold" href="{% url 'groups:all' %}">Groups</a>
        </li>
    </ul>
    <div class="my-2 my-lg-0">
        <a class="mr-sm-2 text-light font-weight-bold" href="{% url 'accounts:login' %}">Login</a>
    </div>
    <div class="my-2 my-lg-0">
        <a class="my-2 my-sm-0 text-light font-weight-bold" href="{% url 'accounts:signup' %}">Sign Up</a>
    </div>
    {% endif %}
  </div>
</nav>

<div class="row justify-content-around fixed-bottom navbar-light bg-info">
        <a class="navbar-brand text-center" href="#">&copy; SocialNetwork</a>
</div>

templates/thanks.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}
{% block main_content %}
  <h1 class="text-center mt-5">Thanks for visiting..... come back soon!!!</h1>
{% endblock main_content %}